version: "3.0"
services:
 mysqldatabase: # name of our service, NOTE: it can be anything you name it
   image: mysql:8.0 # pull from docker public repository if it is not available in your local machine
   ports:
    - 3360:3360 # the ports in the format PORT_WE_EXPOSE:PORT_OF_APPLICATION_IN_CONTAINER
   environment:
    - MYSQL_ROOT_PASSWORD=password #these are the default environments, check https://hub.docker.com/_/mysql/ on allowed environment variables
   networks:
    - desired_network_name # incase your run another container that needs to communicate with this container, make sure they are in the same network
   volumes:
    - desired_mysql_database:/var/lib/mysql # named volume where our mysql persistent volume will reside.
    - /home/kanji/Documents/sql_file.sql:/home/backup.sql # this will load from our local machine to container

    # for the above volumes are in the format LOCAL_MACHINE_LOCATION:LOCATION_INSIDE_OUR_CONTAINER
    # for the first volume, which is named volume, docker will determine suitable location for our persistence on the local machine,
    # location /var/lib/mysql is where our backup in the container will reside, basically mysql inside container will read from this location

networks:
  desired_network_name:

volumes:
  desired_mysql_database:
